version: 2.1

orbs:
  docker: circleci/docker@2.1

jobs:
  build:
    parameters:
      node-version:
        description: Node.js version
        type: string
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - run:
          name: Get latest version and save to job environment variables
          command: |
            # Get the latest full version
            full_version_raw=$(curl -sSL https://nodejs.org/dist/index.json | jq -r "map(select(.lts and (.version | startswith(\"v<< parameters.node-version >>.\"))))[0].version")
            # Get the LTS codename
            lts_raw=$(curl -sSL https://nodejs.org/dist/index.json | jq -r "map(select(.lts and (.version | startswith(\"v<< parameters.node-version >>.\"))))[0].lts | tostring | ascii_downcase")
            [ ! "$lts_raw" = "null" ] && lts=$lts_raw || true
            # Drop the 'v' in front of the version string
            full_version=${full_version_raw:1}
            # Drop the patch version
            major_minor_version=${full_version%.*}
            echo "export NODE_VERSION=${full_version}" >> $BASH_ENV
            echo "export NODE_VERSION_MINOR=${major_minor_version}" >> $BASH_ENV
            echo "export LTS=${lts:-$full_version}" >> $BASH_ENV
      - docker/build:
          extra_build_args: "--build-arg NODE_MAJOR_VERSION=<< parameters.node-version >>"
          image: verdigristech/dev-node
          tag: $NODE_VERSION,$NODE_VERSION_MINOR,<< parameters.node-version >>,$LTS
      - docker/push:
          image: verdigristech/dev-node
          tag: $NODE_VERSION,$NODE_VERSION_MINOR,<< parameters.node-version >>,$LTS
  update-description:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/update-description:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
          image: verdigristech/dev-node

workflows:
  version: 2
  lint:
    jobs:
      - docker/hadolint:
          executor-class: medium
          ignore-rules: DL3059,DL4006
  publish:
    jobs:
      - build:
          context: dockerhub
          matrix:
            parameters:
              node-version: ["12", "14", "16", "18"]
      - update-description:
          context: dockerhub
          requires:
            - build
